version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    # volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mansoor123
      - POSTGRES_USER=mansoor
      - POSTGRES_DB=cascove


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080